baseURL = 'https://gabr1sr.srht.site/'
languageCode = 'en-us'
title = 'gabr1sr'
theme = 'smol'

[params]
subtitle = 'programming'

[menu]
[[menu.main]]
identifier = 'posts'
name = 'Posts'
url = '/posts/'
weight = 1

[[menu.main]]
identifier = 'emacs'
name = 'Emacs'
url = '/tags/emacs/'
weight = 2

[[menu.footer]]
name = 'git'
url = 'https://github.com/gabr1sr'
weight = 1

[[menu.footer]]
name = 'twitter'
url = 'https://twitter.com/gabr1sr'
weight = 2

[markup.goldmark.renderer]
  unsafe = true